In [1]:
from pathlib import Path
from miditok.data_augmentation import augment_dataset

data_path = Path("../data")
tokenized_folder = data_path / "tokenized/"
augmented_folder = data_path / "augmented/"

/opt/miniconda3/envs/music-llm/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
from miditok.constants import SUPPORTED_MUSIC_FILE_EXTENSIONS
music_folder = data_path / "midi/"

files_paths = [
    path
    for path in music_folder.glob("**/*")
    if path.suffix in SUPPORTED_MUSIC_FILE_EXTENSIONS
]

print("File paths", files_paths)

File paths [PosixPath("../data/midi/Don_t_Cry_Gtr._I_|_Guns_n'_Roses.mid"), PosixPath('../data/midi/Estranged_Electric_Guitar.mid'), PosixPath('../data/midi/Paradise_City.1_Electric_Guitar.mid'), PosixPath('../data/midi/Back_Off_Bitch_Gtr._I.mid'), PosixPath('../data/midi/Since_I_Don_t_Have_You_Electric_Guitar.mid'), PosixPath('../data/midi/Don_t_Cry.1_DISTORTION.mid'), PosixPath('../data/midi/Dust_N_Bones.1_Electric_Guitar.mid'), PosixPath('../data/midi/Live_Let_Die.1_DISTORTION.mid'), PosixPath('../data/midi/Knockin_on_Heaven_Door.3_-GnR.mid'), PosixPath('../data/midi/Rocket_Queen_Electric_Guitar.mid'), PosixPath('../data/midi/Nightrain_Slash.mid'), PosixPath('../data/midi/Live_Let_Die_Electric_Guitar.mid'), PosixPath('../data/midi/November_Rain.2_Electric_Guitar.mid'), PosixPath('../data/midi/Locomotive_Electric_Guitar.mid'), PosixPath('../data/midi/Paradise_City_Dst_Gtr.mid'), PosixPath('../data/midi/November_Rain.3_-Slash_-Lead_and_rythem-.mid'), PosixPath('../data/midi/You_Could_

In [8]:
print("tok_dir exists:", tokenized_folder.exists(), "is_dir:", tokenized_folder.is_dir())
print("example files:", [str(p) for p in tokenized_folder.rglob('*.json')][:5])

import tqdm

tok_dir exists: True is_dir: True
example files: ['../data/tokenized/Locomotive_Electric_Guitar.json', '../data/tokenized/Paradise_City.1_Electric_Guitar.json', '../data/tokenized/November_Rain_CLEAN_GTR.json', '../data/tokenized/Dust_N_Bones.1_Electric_Guitar.json', '../data/tokenized/November_Rain.3_-Slash_-Lead_and_rythem-.json']


In [6]:
augment_dataset(
    data_path=music_folder,
    pitch_offsets=[-12, 12],
    velocity_offsets=[-4, 5],
    duration_offsets=[-0.5, 1],
    out_path=augmented_folder,
)

Performing data augmentation: 100%|██████████| 33/33 [00:00<00:00, 270.40it/s]


In [7]:
from src.model.model import Head
import torch

In [13]:
torch.manual_seed(1337)

In [14]:
head = Head(head_size=8, n_embd=32)
head.tril

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 1., 0.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        ...,
        [1., 1., 1.,  ..., 1., 0., 0.],
        [1., 1., 1.,  ..., 1., 1., 0.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [10]:
B, T, C = 4, 8, 32
x = torch.randn((B, T, C))
x

tensor([[[ 3.3299e-01,  1.0995e+00,  4.0335e-01,  ...,  1.6634e+00,
          -4.7180e-01,  5.8567e-01],
         [-9.5790e-01,  9.4345e-01, -2.1992e+00,  ..., -7.2962e-01,
           1.6526e-01, -3.3901e-01],
         [ 1.5416e+00,  1.0231e+00,  1.3392e+00,  ..., -4.3305e-02,
          -2.5050e-01, -7.4927e-01],
         ...,
         [ 7.4498e-01,  7.1704e-01,  1.2668e+00,  ...,  1.9359e+00,
           2.0350e+00,  2.0187e+00],
         [ 3.2340e-02, -6.3372e-01,  2.9381e-01,  ..., -3.2975e-01,
          -1.9170e-02,  9.2251e-01],
         [ 9.1867e-01,  2.9977e-01,  6.1063e-01,  ...,  8.2824e-01,
          -4.8264e-01,  1.8330e+00]],

        [[ 3.4207e-01,  2.1544e-01, -1.0289e-01,  ...,  4.5889e-01,
          -6.5318e-01,  1.1831e+00],
         [-3.6659e-01,  4.4723e-01, -2.8425e-01,  ..., -9.2288e-01,
           2.3084e-01, -7.5861e-01],
         [-1.6410e+00, -1.3728e+00, -1.3389e+00,  ...,  9.2413e-01,
          -5.1309e-01, -7.6122e-01],
         ...,
         [ 7.7094e-01,  6

In [11]:
out = head.forward(x)
out.shape

torch.Size([4, 8, 8])

In [12]:
out[0][0]

tensor([nan, nan, nan, nan, nan, nan, nan, nan], grad_fn=<SelectBackward0>)

In [7]:
print(head.wei[0][3])

tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan], grad_fn=<SelectBackward0>)
